### ISSUE TITLE
v1.0.5 Fragment中onCreateView（）如何return？

### ISSUE THREAD

**Issue by viatomEcho** [hi-dhl/JDataBinding#6]
使用1.0.5，在fragment中的onCreateView 方法该如何返回？ 如果 return binding.root，则
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
        at com.lepu.demo.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:41)
        at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at androidx.databinding.ViewDataBinding.bind(ViewDataBinding.java:695)
        at com.lepu.demo.databinding.FragmentHomeBinding.bind(FragmentHomeBinding.java:95)

**Comment by hi-dhl** [comment]
这个处理的方案，可以参考我另外一个库 https://github.com/hi-dhl/Binding 的处理，  Binding 和 JDataBinding 是互相兼容的，也可以使用 Binding 替换掉 JDataBinding， Binding 更加全面

```
class FragmentNav1 : Fragment() {
    
    // DataBinding
  	val binding: FragmentMainBinding by databind()
    
    // ViewBinding
  	 val binding: FragmentMainBinding by viewbind()
  
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return binding.root
    }
}
```
